const startupMockData = [
  {
    Id: 1,
    founderName: 'Rajesh Kumar',
    founderEmail: 'rajesh@ecotech.com',
    founderPhone: '+91 9876543210',
    founderExperience: '5',
    businessName: 'EcoTech Solutions',
    businessType: 'manufacturing',
    businessIdea: 'Sustainable packaging solutions using biodegradable materials sourced from agricultural waste',
    businessStage: 'prototype',
    businessLocation: 'Bhubaneswar, Khordha, Odisha',
    status: 'active',
    onboardingComplete: true,
    registrationDate: '2024-01-15T10:30:00Z',
    nextStep: 'completed',
    pitchDeckRequired: true,
    mentorshipRequired: true,
    fundingRequired: true,
    complianceConsent: true,
    dataProcessingConsent: true,
    kycStatus: 'approved',
    paymentStatus: 'completed',
    complianceScore: 85
  },
  {
    Id: 2,
    founderName: 'Priya Sharma',
    founderEmail: 'priya@greenmarket.com',
    founderPhone: '+91 9876543211',
    founderExperience: '3',
    businessName: 'Green Market Hub',
    businessType: 'fmcg_distribution',
    businessIdea: 'Online marketplace for organic and locally sourced FMCG products',
    businessStage: 'mvp',
    businessLocation: 'Cuttack, Cuttack, Odisha',
    status: 'active',
    onboardingComplete: true,
    registrationDate: '2024-01-20T14:15:00Z',
    nextStep: 'completed',
    pitchDeckRequired: false,
    mentorshipRequired: true,
    fundingRequired: false,
    complianceConsent: true,
    dataProcessingConsent: true,
    kycStatus: 'approved',
    paymentStatus: 'completed',
    complianceScore: 92
  },
  {
    Id: 3,
    founderName: 'Amit Patel',
    founderEmail: 'amit@techstream.com',
    founderPhone: '+91 9876543212',
    founderExperience: '7',
    businessName: 'TechStream Engineering',
    businessType: 'engineering_goods',
    businessIdea: 'Distribution of IoT-enabled engineering equipment for smart manufacturing',
    businessStage: 'pilot',
    businessLocation: 'Rourkela, Sundargarh, Odisha',
    status: 'active',
    onboardingComplete: true,
    registrationDate: '2024-01-25T09:45:00Z',
    nextStep: 'completed',
    pitchDeckRequired: true,
    mentorshipRequired: false,
    fundingRequired: true,
    complianceConsent: true,
    dataProcessingConsent: true,
    kycStatus: 'approved',
    paymentStatus: 'completed',
    complianceScore: 78
  },
  {
    Id: 4,
    founderName: 'Sneha Das',
    founderEmail: 'sneha@digitalcraft.com',
    founderPhone: '+91 9876543213',
    founderExperience: '4',
    businessName: 'Digital Craft Studios',
    businessType: 'digital_services',
    businessIdea: 'Digital marketing and e-commerce solutions for traditional businesses',
    businessStage: 'launch',
    businessLocation: 'Berhampur, Ganjam, Odisha',
    status: 'pending',
    onboardingComplete: false,
    registrationDate: '2024-02-01T11:20:00Z',
    nextStep: 'kyc',
    pitchDeckRequired: false,
    mentorshipRequired: true,
    fundingRequired: false,
    complianceConsent: true,
    dataProcessingConsent: true,
    kycStatus: 'pending',
    paymentStatus: 'pending',
    complianceScore: 65
  },
  {
    Id: 5,
    founderName: 'Vikash Singh',
    founderEmail: 'vikash@agritech.com',
    founderPhone: '+91 9876543214',
    founderExperience: '6',
    businessName: 'AgriTech Innovations',
    businessType: 'manufacturing',
    businessIdea: 'Smart farming equipment and precision agriculture solutions',
    businessStage: 'idea',
    businessLocation: 'Sambalpur, Sambalpur, Odisha',
    status: 'pending',
    onboardingComplete: false,
    registrationDate: '2024-02-05T16:30:00Z',
    nextStep: 'payment',
    pitchDeckRequired: true,
    mentorshipRequired: true,
    fundingRequired: true,
    complianceConsent: true,
    dataProcessingConsent: true,
    kycStatus: 'approved',
    paymentStatus: 'pending',
    complianceScore: 70
  }
];

export default startupMockData;