const startupApplications = [
  {
    Id: 1,
    founderName: 'Arjun Patel',
    email: 'arjun.patel@email.com',
    phone: '+91 9876543210',
    businessName: 'EcoFresh Foods',
    startupType: 'fmcg_manufacturing',
    productCategory: 'Organic Food Products',
    businessIdea: 'Manufacturing organic ready-to-eat meals using locally sourced ingredients from Odisha farmers. Focus on traditional Odia recipes with modern packaging.',
    investmentAmount: '15 lakhs',
    timeline: '6 months',
    status: 'pending',
    submittedAt: '2024-01-15T10:30:00Z',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z'
  },
  {
    Id: 2,
    founderName: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91 9123456789',
    businessName: 'Coastal Distributors',
    startupType: 'micro_distributor',
    distributionArea: 'Puri District',
    productCategories: 'FMCG, Healthcare, Electronics',
    businessIdea: 'Establishing a micro-distribution network covering coastal areas of Puri district, focusing on last-mile delivery to remote villages.',
    investmentAmount: '8 lakhs',
    timeline: '3 months',
    status: 'approved',
    submittedAt: '2024-01-10T14:20:00Z',
    createdAt: '2024-01-10T14:20:00Z',
    updatedAt: '2024-01-12T09:15:00Z'
  },
  {
    Id: 3,
    founderName: 'Rahul Kumar',
    email: 'rahul.kumar@email.com',
    phone: '+91 9876512345',
    businessName: 'TechSolutions Odisha',
    startupType: 'digital_entrepreneur',
    serviceType: 'E-commerce Platform',
    targetMarket: 'B2B and B2C',
    businessIdea: 'Creating a comprehensive e-commerce platform connecting Odisha artisans and small businesses with global markets, featuring local handicrafts and traditional products.',
    investmentAmount: '12 lakhs',
    timeline: '4 months',
    status: 'under_review',
    submittedAt: '2024-01-08T16:45:00Z',
    createdAt: '2024-01-08T16:45:00Z',
    updatedAt: '2024-01-08T16:45:00Z'
  },
  {
    Id: 4,
    founderName: 'Sneha Mishra',
    email: 'sneha.mishra@email.com',
    phone: '+91 9345678901',
    businessName: 'Handloom Heritage',
    startupType: 'fmcg_manufacturing',
    productCategory: 'Textile and Apparel',
    businessIdea: 'Manufacturing premium handloom textile products using traditional Odia weaving techniques, targeting both domestic and international markets.',
    investmentAmount: '20 lakhs',
    timeline: '8 months',
    status: 'pending',
    submittedAt: '2024-01-05T11:30:00Z',
    createdAt: '2024-01-05T11:30:00Z',
    updatedAt: '2024-01-05T11:30:00Z'
  },
  {
    Id: 5,
    founderName: 'Vikash Jena',
    email: 'vikash.jena@email.com',
    phone: '+91 9234567890',
    businessName: 'Smart Logistics Hub',
    startupType: 'micro_distributor',
    distributionArea: 'Bhubaneswar Metropolitan',
    productCategories: 'E-commerce, Pharmaceuticals, Groceries',
    businessIdea: 'Technology-enabled micro-distribution hub providing same-day delivery services for e-commerce, pharmaceuticals, and grocery items in Bhubaneswar.',
    investmentAmount: '25 lakhs',
    timeline: '5 months',
    status: 'approved',
    submittedAt: '2024-01-03T13:15:00Z',
    createdAt: '2024-01-03T13:15:00Z',
    updatedAt: '2024-01-04T10:20:00Z'
  }
];

export default startupApplications;